#!/bin/sh
# Regenerates the RFC 3161 test fixtures with `openssl ts`. Run from the repo root after
# `npm run build`:   sh test/fixtures/rfc3161/generate.sh
#
# TEST-ONLY KEYS. Every private key in this folder (keys/*.key) was generated for these
# fixtures, protects nothing, and must never be trusted for anything. The CA is
# "VeilCore TEST ONLY Root"; nothing anywhere should ever chain to it.
#
# SPDX-License-Identifier: Apache-2.0
set -eu
D=$(cd "$(dirname "$0")" && pwd)
cd "$D"
rm -rf keys certs tokens work && mkdir -p keys certs tokens work
printf '%s\n' 'TEST-ONLY KEYS. Generated by generate.sh for the RFC 3161 test fixtures.' \
  'They protect nothing. Never trust anything signed by them or chaining to certs/ca.pem.' > keys/TEST-ONLY-KEYS.txt

# What is stamped: the 32 raw bytes of a record's commitment (SPEC 3.2), here the
# commitment of record.json. A TSA client submits the SHA-256 of those 32 bytes.
node -e '
  import("'"$D"'/../../../dist/index.js").then(async (m) => {
    const fs = await import("node:fs");
    const r = JSON.parse(fs.readFileSync("record.json", "utf8"));
    r.commitment = await m.computeCommitment(r);
    fs.writeFileSync("record.json", JSON.stringify(r, null, 2) + "\n");
    fs.writeFileSync("stamped.bin", Buffer.from(r.commitment, "hex"));
    // A batch containing it, for a token that stamps the batch root instead.
    const others = ["a", "b"].map((x) => (x.repeat(64)));
    const b = await m.buildBatch([others[0], r.commitment, others[1]], "B-RFC3161-FIXTURE", "2026-10-03T12:05:00Z");
    fs.writeFileSync("proof.json", JSON.stringify(b.proofs[r.commitment], null, 2) + "\n");
    fs.writeFileSync("root.bin", Buffer.from(b.root, "hex"));
  });'
head -c 32 /dev/zero > other.bin

cat > work/ext.cnf <<'X'
[ca]
basicConstraints = critical, CA:TRUE
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
[tsa]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, nonRepudiation
extendedKeyUsage = critical, timeStamping
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
[noeku]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, nonRepudiation
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
X

openssl req -x509 -newkey rsa:2048 -nodes -keyout keys/ca.key -out certs/ca.pem -days 36500 \
  -subj "/C=US/O=VeilCore TEST ONLY/CN=VeilCore TEST ONLY Root" -extensions ca -config work/ext.cnf -set_serial 1 2>/dev/null \
  || openssl req -x509 -newkey rsa:2048 -nodes -keyout keys/ca.key -out certs/ca.pem -days 36500 \
  -subj "/C=US/O=VeilCore TEST ONLY/CN=VeilCore TEST ONLY Root" -addext "basicConstraints=critical,CA:TRUE" -addext "keyUsage=critical,keyCertSign,cRLSign" -set_serial 1

issue () { # name keyspec serial ext
  case "$2" in
    rsa) openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out keys/$1.key 2>/dev/null ;;
    *) openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:$2 -out keys/$1.key ;;
  esac
  openssl req -new -key keys/$1.key -subj "/C=US/O=VeilCore TEST ONLY/CN=TEST TSA $1" -out work/$1.csr
  openssl x509 -req -in work/$1.csr -CA certs/ca.pem -CAkey keys/ca.key -set_serial $3 -days 36500 \
    -extfile work/ext.cnf -extensions $4 -out certs/$1.pem 2>/dev/null
}
issue tsa-rsa rsa 101 tsa
issue tsa-p256 P-256 102 tsa
issue tsa-p384 P-384 103 tsa
issue tsa-p521 P-521 104 tsa
# Same key, issuer and serial as tsa-rsa, but no timeStamping EKU. openssl refuses to sign
# with it, so the test swaps it into an RSA token in place of the real certificate (the
# certificate set is not covered by the signature, so only the EKU check can catch it).
openssl x509 -req -in work/tsa-rsa.csr -CA certs/ca.pem -CAkey keys/ca.key -set_serial 101 -days 36500 \
  -extfile work/ext.cnf -extensions noeku -out certs/tsa-rsa-noeku.pem 2>/dev/null
openssl x509 -in certs/tsa-rsa-noeku.pem -outform DER -out certs/tsa-rsa-noeku.der

reply () { # out key-name query-hash signer-digest data
  cat > work/ts.cnf <<X
[tsa]
default_tsa = t
[t]
serial = work/serial
signer_cert = certs/$2.pem
certs = certs/ca.pem
signer_key = keys/$2.key
signer_digest = $4
default_policy = 1.3.6.1.4.1.99999.1
digests = sha1, sha256, sha384, sha512
accuracy = secs:1
ordering = no
tsa_name = yes
ess_cert_id_chain = no
ess_cert_id_alg = sha256
X
  [ -f work/serial ] || echo 01 > work/serial
  openssl ts -query -data ${5:-stamped.bin} -$3 -cert -out work/$1.tsq 2>/dev/null
  openssl ts -reply -config work/ts.cnf -queryfile work/$1.tsq -out tokens/$1.tsr 2>/dev/null
  openssl ts -reply -in tokens/$1.tsr -token_out -out tokens/$1.tst 2>/dev/null
  # Independent check with openssl itself (the chain is checked here, against the test CA).
  openssl ts -verify -data ${5:-stamped.bin} -in tokens/$1.tst -token_in -CAfile certs/ca.pem >/dev/null 2>&1
}
reply rsa-sha256 tsa-rsa sha256 sha256
reply rsa-sha512 tsa-rsa sha512 sha384
reply p256-sha256 tsa-p256 sha256 sha256
reply p384-sha384 tsa-p384 sha384 sha384
reply p521-sha256 tsa-p521 sha256 sha512
reply rsa-sha1-signer tsa-rsa sha256 sha1
reply rsa-sha1-imprint tsa-rsa sha1 sha256
reply batch-p256 tsa-p256 sha256 sha256 root.bin
for c in ca tsa-rsa tsa-p256 tsa-p384 tsa-p521; do openssl x509 -in certs/$c.pem -outform DER -out certs/$c.der; done
rm -rf work
echo "fixtures written to $D"
